apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prefect.fullname" . }}
  labels:
    {{- include "prefect.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "prefect.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "prefect.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["prefect", "server", "start"]
          ports:
            - name: http
              containerPort: 4200
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}