apiVersion: v1
kind: Service
metadata:
  name: {{ include "prefect.fullname" . }}-server
  labels:
    {{- include "prefect.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prefect.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
